# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class ServiceRequestStatsSchemaAreaStats(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ServiceRequestStatsSchemaAreaStats - a model defined in OpenAPI

        count: The count of this ServiceRequestStatsSchemaAreaStats [Optional].
        open: The open of this ServiceRequestStatsSchemaAreaStats [Optional].
        duration_p50: The duration_p50 of this ServiceRequestStatsSchemaAreaStats [Optional].
        heatmap_link: The heatmap_link of this ServiceRequestStatsSchemaAreaStats [Optional].
        last_updated: The last_updated of this ServiceRequestStatsSchemaAreaStats [Optional].
    """

    count: Optional[int] = Field(alias="count", default=None)
    open: Optional[int] = Field(alias="open", default=None)
    duration_p50: Optional[int] = Field(alias="duration_p50", default=None)
    heatmap_link: Optional[str] = Field(alias="heatmap_link", default=None)
    last_updated: Optional[datetime] = Field(alias="last_updated", default=None)

ServiceRequestStatsSchemaAreaStats.update_forward_refs()
