# coding: utf-8

"""
    Service Request Info API

    This is a radically open, non-authed API intended to provide information on service requests to the residents of Cape Town

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from fastapi import FastAPI

from coct_sr_info_server.apis.classification_api import router as ClassificationApiRouter
from coct_sr_info_server.apis.service_request_info_api import router as ServiceRequestInfoApiRouter
from coct_sr_info_server.logic import utils

app = FastAPI(
    title="Service Request Info API",
    description="This is a radically open, non-authed API intended to provide information on service requests "
                "to the residents of Cape Town",
    version="1.0.0",
    debug=True
)

app.include_router(ClassificationApiRouter)
app.include_router(ServiceRequestInfoApiRouter)

logger = utils.get_logger()
logger.info("Server starting up!")
